name: Test Arkime Plugin Configuration Script

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Lua
      uses: leafo/setup-lua@v1
      with:
        luaVersion: "5.4.4"
    - name: Run Configuration Script for Each Case
      run: |
    	echo "running tests" 
        lua /home/celinechan/Desktop/Repo/ArkimePlugins-Internship/JA4FindReplacePluginLine.lua case1.ini
        lua /home/celinechan/Desktop/Repo/ArkimePlugins-Internship/JA4FindReplacePluginLine.lua case2.ini
        lua /home/celinechan/Desktop/Repo/ArkimePlugins-Internship/JA4FindReplacePluginLine.lua case3.ini
        lua /home/celinechan/Desktop/Repo/ArkimePlugins-Internship/JA4FindReplacePluginLine.lua case4.ini
        lua /home/celinechan/Desktop/Repo/ArkimePlugins-Internship/JA4FindReplacePluginLine.lua case5.ini
      shell: bash

    - name: Check Outputs
      run: |
        for i in {1..5}; do
          echo "Case $i Output:"
          cat rancase_case$i.ini
        done

