name: luaRocks Test

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v10
      - uses: leafo/gh-actions-luarocks@v4
      # Runs a set of commands using the runner's shell
      - name: install
        run: |
          luarocks install \
            --deps-only lua-series-1.1.0-1.rockspec
      - name: test addition lua Function
        run: luarocks test /home/celinechan/Desktop/Repo/ArkimePlugins-Internship/testFunction.lua
        env:
          LUA_INIT: "@src/setup.lua"

