name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: "5.1"

    - uses: leafo/gh-actions-luarocks@v4

    - name: linting rockspec
      run: |
        luarocks lint lua-dev-1.rockspec

    - name: install dependencies
      run: |
        luarocks install --deps-only lua-dev-1.rockspec
        
    - name: run main.lua
      run: |
        lua -l src/setup src/main.lua

    - name: run test.lua
      run: luarocks test
      env:
        LUA_INIT: "@src/setup.lua"
        
